# Generated by Django 3.0.3 on 2020-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pricing_app", "0002_product_image")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        )
    ]
